version: '3.8'

services:
  github-runner:
    image: myoung34/github-runner:latest
    container_name: usav_github_runner
    restart: unless-stopped
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/USAV_ERP:/docker/USAV_ERP
    environment:
      - REPO_URL=https://github.com/USAV-Solutions/USAV_ERP
      - RUNNER_TOKEN=${RUNNER_TOKEN:-BEDCJ45FUADDALK2JC74FXLKOX7F4}
      - RUNNER_NAME=${RUNNER_NAME:-synology-ds220-runner}
