#!/usr/bin/env python
# pyright: reportMissingImports=false
"""Build image URL candidates for backfill tasks.

Input: task JSON generated by generate_image_tasks.py
Output: downloader-ready JSON rows:
[
  {
    "sku": "00002-BK",
    "platform": "ECWID",
    "external_id": "123456789",
    "image_urls": ["https://..."],
    "sources": ["platform_metadata", "ecwid_api"]
  }
]

Sources used:
- platform_listing.platform_metadata (if available)
- Ecwid Product API (optional)
- eBay Browse API legacy item lookup (optional)
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re
import sys
from pathlib import Path
from typing import Any

import httpx
from sqlalchemy import select

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from app.core.config import settings
from app.core.database import async_session_factory
from app.integrations.ebay.client import EbayClient
from app.models import Platform, PlatformListing


_IMAGE_EXTS = (".jpg", ".jpeg", ".png", ".webp")
_IMAGE_HINT_KEYS = {
    "image",
    "images",
    "imageurl",
    "image_url",
    "picture",
    "pictures",
    "gallery",
    "thumbnail",
    "thumbnailurl",
    "originalimageurl",
    "url",
}


def _looks_like_url(value: str) -> bool:
    v = value.strip()
    return v.startswith("http://") or v.startswith("https://")


def _looks_like_image_url(value: str) -> bool:
    v = value.lower()
    if any(v.endswith(ext) for ext in _IMAGE_EXTS):
        return True
    if any(token in v for token in (".jpg?", ".jpeg?", ".png?", ".webp?")):
        return True
    if any(token in v for token in ("image", "images", "thumbnail", "thumb", "gallery")):
        return True
    return False


def _normalize_url(value: str) -> str:
    return value.strip()


def _extract_urls_recursive(payload: Any) -> list[str]:
    found: set[str] = set()

    def walk(node: Any, parent_key: str | None = None) -> None:
        if isinstance(node, dict):
            for key, value in node.items():
                walk(value, parent_key=str(key).lower())
            return

        if isinstance(node, list):
            for value in node:
                walk(value, parent_key=parent_key)
            return

        if isinstance(node, str):
            val = _normalize_url(node)
            if not _looks_like_url(val):
                return

            key_hint = (parent_key or "").replace("-", "").replace("_", "")
            hinted = key_hint in _IMAGE_HINT_KEYS
            if hinted or _looks_like_image_url(val):
                found.add(val)

    walk(payload)
    return sorted(found)


async def _load_platform_metadata_by_listing_id(listing_ids: list[int]) -> dict[int, dict]:
    if not listing_ids:
        return {}

    async with async_session_factory() as db:
        rows = (
            await db.execute(
                select(PlatformListing.id, PlatformListing.platform_metadata)
                .where(PlatformListing.id.in_(listing_ids))
            )
        ).all()

    result: dict[int, dict] = {}
    for row in rows:
        metadata = row.platform_metadata or {}
        if isinstance(metadata, dict):
            result[int(row.id)] = metadata
    return result


def _ebay_client_for_platform(platform: str) -> EbayClient | None:
    store = platform.replace("EBAY_", "")
    token_map = {
        "EBAY_MEKONG": settings.ebay_refresh_token_mekong,
        "EBAY_USAV": settings.ebay_refresh_token_usav,
        "EBAY_DRAGON": settings.ebay_refresh_token_dragon,
    }
    refresh_token = token_map.get(platform, "")
    if not all([settings.ebay_app_id, settings.ebay_cert_id, refresh_token]):
        return None

    return EbayClient(
        store_name=store,
        app_id=settings.ebay_app_id,
        cert_id=settings.ebay_cert_id,
        refresh_token=refresh_token,
        sandbox=settings.ebay_sandbox,
    )


async def _fetch_ecwid_urls(external_id: str) -> list[str]:
    if not settings.ecwid_store_id or not settings.ecwid_secret:
        return []

    url = f"{settings.ecwid_api_base_url}/{settings.ecwid_store_id}/products/{external_id}"
    headers = {
        "Authorization": f"Bearer {settings.ecwid_secret}",
        "Accept": "application/json",
    }
    try:
        async with httpx.AsyncClient(timeout=20.0) as client:
            resp = await client.get(url, headers=headers)
            resp.raise_for_status()
            payload = resp.json()
    except Exception:
        return []

    return _extract_urls_recursive(payload)


async def _fetch_ebay_urls(platform: str, external_id: str) -> list[str]:
    client = _ebay_client_for_platform(platform)
    if client is None:
        return []

    try:
        access_token = await client._get_access_token()  # noqa: SLF001
    except Exception:
        return []

    if not access_token:
        return []

    headers = {
        "Authorization": f"Bearer {access_token}",
        "Accept": "application/json",
        "X-EBAY-C-MARKETPLACE-ID": "EBAY_US",
    }
    endpoint = f"{client.base_url}/buy/browse/v1/item/get_item_by_legacy_id"

    try:
        async with httpx.AsyncClient(timeout=20.0) as http:
            resp = await http.get(endpoint, headers=headers, params={"legacy_item_id": external_id})
            resp.raise_for_status()
            payload = resp.json()
    except Exception:
        return []

    return _extract_urls_recursive(payload)


def _parse_platforms(raw: str | None) -> set[str] | None:
    if not raw:
        return None
    parsed = {token.strip().upper() for token in raw.split(",") if token.strip()}
    return parsed or None


async def _run(args: argparse.Namespace) -> None:
    input_path = Path(args.input)
    output_path = Path(args.output)
    rows = json.loads(input_path.read_text(encoding="utf-8"))

    allowed_platforms = _parse_platforms(args.platforms)
    if allowed_platforms is not None:
        rows = [r for r in rows if (r.get("platform") or "").upper() in allowed_platforms]

    if args.limit is not None:
        rows = rows[: args.limit]

    listing_ids = [
        int(row["listing_id"])
        for row in rows
        if row.get("listing_id") is not None and str(row.get("listing_id")).isdigit()
    ]

    metadata_by_listing = {}
    if args.include_platform_metadata:
        metadata_by_listing = await _load_platform_metadata_by_listing_id(listing_ids)

    output_rows: list[dict] = []
    stats = {
        "tasks": 0,
        "with_urls": 0,
        "empty": 0,
        "from_metadata": 0,
        "from_ecwid": 0,
        "from_ebay": 0,
    }

    for row in rows:
        stats["tasks"] += 1

        sku = (row.get("sku") or "").strip()
        platform = (row.get("platform") or "").strip().upper()
        external_id = (row.get("external_id") or "").strip()
        listing_id = row.get("listing_id")

        if not sku or not platform or not external_id:
            continue

        urls: set[str] = set()
        sources: list[str] = []

        if args.include_platform_metadata and listing_id is not None:
            try:
                listing_id_int = int(listing_id)
            except Exception:
                listing_id_int = None

            if listing_id_int is not None:
                metadata = metadata_by_listing.get(listing_id_int) or {}
                meta_urls = _extract_urls_recursive(metadata)
                if meta_urls:
                    urls.update(meta_urls)
                    sources.append("platform_metadata")
                    stats["from_metadata"] += 1

        if args.fetch_ecwid and platform == Platform.ECWID.value:
            ecwid_urls = await _fetch_ecwid_urls(external_id)
            if ecwid_urls:
                urls.update(ecwid_urls)
                sources.append("ecwid_api")
                stats["from_ecwid"] += 1

        if args.fetch_ebay and platform.startswith("EBAY_"):
            ebay_urls = await _fetch_ebay_urls(platform, external_id)
            if ebay_urls:
                urls.update(ebay_urls)
                sources.append("ebay_browse_api")
                stats["from_ebay"] += 1

        image_urls = sorted(urls)
        if not image_urls and not args.include_empty:
            stats["empty"] += 1
            continue

        if image_urls:
            stats["with_urls"] += 1
        else:
            stats["empty"] += 1

        output_rows.append(
            {
                "sku": sku,
                "platform": platform,
                "external_id": external_id,
                "image_urls": image_urls,
                "sources": sources,
            }
        )

        if args.delay_ms > 0:
            await asyncio.sleep(args.delay_ms / 1000.0)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(output_rows, indent=2), encoding="utf-8")

    print(f"Input tasks processed: {stats['tasks']}")
    print(f"Output rows: {len(output_rows)}")
    print(f"Rows with image URLs: {stats['with_urls']}")
    print(f"Rows without image URLs: {stats['empty']}")
    print(f"Rows with metadata source hits: {stats['from_metadata']}")
    print(f"Rows with Ecwid API source hits: {stats['from_ecwid']}")
    print(f"Rows with eBay API source hits: {stats['from_ebay']}")
    print(f"Wrote: {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build image URL candidates from tasks")
    parser.add_argument("--input", required=True, help="Task JSON input path")
    parser.add_argument("--output", required=True, help="URL candidate JSON output path")
    parser.add_argument("--platforms", default=None, help="Optional comma-separated platforms filter")
    parser.add_argument("--limit", type=int, default=None, help="Optional max tasks to process")
    parser.add_argument("--include-empty", action="store_true", help="Keep rows with empty image_urls")

    parser.add_argument("--include-platform-metadata", action="store_true", help="Extract image URLs from platform_listing.platform_metadata")
    parser.add_argument("--fetch-ecwid", action="store_true", help="Call Ecwid Product API for ECWID tasks")
    parser.add_argument("--fetch-ebay", action="store_true", help="Call eBay Browse API for EBAY_* tasks")
    parser.add_argument("--delay-ms", type=int, default=0, help="Delay between row fetches in milliseconds")

    args = parser.parse_args()
    asyncio.run(_run(args))


if __name__ == "__main__":
    main()
