"""add physical_scans table

Revision ID: 469482e42773
Revises: 0035
Create Date: 2026-06-16 12:29:28.535751+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '469482e42773'
down_revision: Union[str, None] = '0035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('physical_scans',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=False, comment='The scanned barcode/tracking number.'),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='When the barcode was physically scanned.'),
    sa.Column('scanned_by', sa.String(length=50), nullable=True, comment='Name or username of the operator (or chat bot ID).'),
    sa.Column('is_matched', sa.Boolean(), server_default='false', nullable=False, comment='Whether a matching order was found in the database at the time of scan.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_physical_scans_scanned_at', 'physical_scans', ['scanned_at'], unique=False)
    op.create_index('ix_physical_scans_tracking', 'physical_scans', ['tracking_number'], unique=False)
    op.create_index(op.f('ix_physical_scans_tracking_number'), 'physical_scans', ['tracking_number'], unique=False)
    op.alter_column('bundle_component', 'quantity_required',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='How many of this component are needed.',
               existing_nullable=False)
    op.alter_column('bundle_component', 'role',
               existing_type=postgresql.ENUM('Primary', 'Accessory', 'Satellite', name='bundle_role_enum'),
               server_default=None,
               existing_comment='Context: Primary, Accessory, Satellite.',
               existing_nullable=False)
    op.alter_column('customer', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='Latest known customer acquisition source (ECWID_API, WALMART_API, SHIPSTATION_CSV, etc.).',
               existing_nullable=True)
    op.alter_column('customer', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment="Soft-delete flag; maps to Zoho 'inactive' status.",
               existing_nullable=False)
    op.alter_column('integration_state', 'platform_name',
               existing_type=sa.VARCHAR(length=50),
               comment="Logical platform key, e.g. 'AMAZON', 'EBAY_USAV'.",
               existing_comment='Logical platform key, e.g. AMAZON, EBAY_USAV.',
               existing_nullable=False)
    op.alter_column('inventory_item', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'SOLD', 'RESERVED', 'RMA', 'DAMAGED', name='inventory_status_enum'),
               server_default=None,
               existing_comment='AVAILABLE, SOLD, RESERVED, RMA, DAMAGED.',
               existing_nullable=False)
    op.alter_column('order_item', 'platform_listing_id',
               existing_type=sa.BIGINT(),
               comment='Resolved platform listing for this order line.',
               existing_nullable=True)
    op.alter_column('order_item', 'variant_id',
               existing_type=sa.BIGINT(),
               comment='Denormalized matched variant for query speed.',
               existing_comment='Matched internal product variant.',
               existing_nullable=True)
    op.alter_column('order_item', 'total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Total price (quantity × unit_price).',
               existing_comment='Total price (quantity * unit_price).',
               existing_nullable=False)
    op.alter_column('orders', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment='Order ingestion source (ECWID_API, WALMART_API, CSV_GENERIC, etc.).',
               existing_nullable=False,
               existing_server_default=sa.text("'MANUAL'::character varying"))
    op.alter_column('orders', 'fulfillment_channel',
               existing_type=postgresql.ENUM('SELF_FULFILLED', 'AMAZON_FBA', name='order_fulfillment_channel_enum'),
               comment='SELF_FULFILLED or AMAZON_FBA.',
               existing_nullable=False,
               existing_server_default=sa.text("'SELF_FULFILLED'::order_fulfillment_channel_enum"))
    op.alter_column('orders', 'zoho_sync_status',
               existing_type=postgresql.ENUM('PENDING', 'SYNCED', 'ERROR', 'DIRTY', name='zoho_sync_status_enum'),
               server_default=None,
               existing_comment='Outbound Zoho sync status.',
               existing_nullable=False)
    op.drop_index(op.f('ix_orders_external_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_ordered_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_platform'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_constraint(op.f('uq_orders_platform_external_id'), 'orders', type_='unique')
    op.create_index('ix_order_external_id', 'orders', ['external_order_id'], unique=False)
    op.create_index('ix_order_ordered_at', 'orders', ['ordered_at'], unique=False)
    op.create_index('ix_order_platform', 'orders', ['platform'], unique=False)
    op.create_index('ix_order_status', 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_zoho_id'), 'orders', ['zoho_id'], unique=False)
    op.create_unique_constraint('uq_order_platform_external_id', 'orders', ['platform', 'external_order_id'])
    op.alter_column('platform_listing', 'variant_id',
               existing_type=sa.BIGINT(),
               comment='Matched internal SKU variant; NULL means unresolved listing.',
               existing_comment='The specific item being sold.',
               existing_nullable=True)
    op.alter_column('platform_listing', 'external_ref_id',
               existing_type=sa.VARCHAR(length=100),
               comment='Canonical platform listing ID (not merchant SKU).',
               existing_comment='The ID on the remote platform (Zoho Item ID, ASIN).',
               existing_nullable=True)
    op.alter_column('platform_listing', 'merchant_sku',
               existing_type=sa.VARCHAR(length=100),
               comment='Marketplace merchant SKU for fallback lookup only.',
               existing_nullable=True)
    op.alter_column('platform_listing', 'listing_quantity',
               existing_type=sa.INTEGER(),
               comment='Channel-specific listing quantity/stock shown on platform.',
               existing_nullable=True)
    op.alter_column('platform_listing', 'listing_type',
               existing_type=sa.VARCHAR(length=100),
               comment='Platform-specific listing type/classification label.',
               existing_nullable=True)
    op.alter_column('platform_listing', 'listing_condition',
               existing_type=sa.VARCHAR(length=100),
               comment='Platform-specific condition label/value as raw string.',
               existing_nullable=True)
    op.alter_column('platform_listing', 'upc',
               existing_type=sa.VARCHAR(length=64),
               comment='UPC/GTIN used by marketplace listing.',
               existing_nullable=True)
    op.alter_column('platform_listing', 'sync_status',
               existing_type=postgresql.ENUM('PENDING', 'SYNCED', 'ERROR', name='platform_sync_status_enum'),
               server_default=None,
               existing_comment='PENDING (needs push), SYNCED (clean), ERROR (retrying).',
               existing_nullable=False)
    op.alter_column('product_family', 'family_code',
               existing_type=sa.VARCHAR(length=5),
               comment='Zero-padded family code derived from product_id (e.g., 00001).',
               existing_nullable=False)
    op.drop_index(op.f('ix_product_family_base_name_fts'), table_name='product_family', postgresql_using='gin')
    op.alter_column('product_identity', 'type',
               existing_type=postgresql.ENUM('Product', 'B', 'P', 'K', 'S', name='identity_type_enum'),
               comment='Product (standard), B (Bundle), P (Part), K (Kit).',
               existing_comment='B (Bundle), P (Part), K (Kit), S (Service), Base (Product).',
               existing_nullable=False)
    op.alter_column('product_identity', 'identity_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Human-friendly identity name (e.g., group or component identity name).',
               existing_nullable=True)
    op.alter_column('product_identity', 'dimension_length',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Identity length in inches.',
               existing_nullable=True)
    op.alter_column('product_identity', 'dimension_width',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Identity width in inches.',
               existing_nullable=True)
    op.alter_column('product_identity', 'dimension_height',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Identity height in inches.',
               existing_nullable=True)
    op.alter_column('product_identity', 'weight',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Identity weight in pounds.',
               existing_nullable=True)
    op.alter_column('product_identity', 'is_stationery',
               existing_type=sa.BOOLEAN(),
               comment='Flags stationery items. Stationery identities must be Product type and single-SKU.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_identity_identity_name'), table_name='product_identity')
    op.alter_column('product_variant', 'condition_code',
               existing_type=postgresql.ENUM('N', 'R', 'U', name='condition_code_enum'),
               comment='N (New), R (Refurbished), U (Used), or NULL.',
               existing_comment='N (New), R (Repair), or NULL (Used/Default).',
               existing_nullable=True)
    op.alter_column('product_variant', 'zoho_sync_status',
               existing_type=postgresql.ENUM('PENDING', 'SYNCED', 'ERROR', 'DIRTY', name='zoho_sync_status_enum'),
               server_default=None,
               existing_comment='Sync status with Zoho.',
               existing_nullable=False)
    op.alter_column('product_variant', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='Soft-delete flag for discontinued variants.',
               existing_nullable=False)
    op.drop_index(op.f('ix_product_variant_full_sku_fts'), table_name='product_variant', postgresql_using='gin')
    op.drop_index(op.f('ix_product_variant_variant_name_fts'), table_name='product_variant', postgresql_using='gin')
    op.alter_column('purchase_order', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchase_order_item', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchase_order_item', 'total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment='Unique username for login.',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='User email address (optional).',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment='Bcrypt hashed password.',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               comment='Display name.',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'WAREHOUSE_OP', 'SALES_REP', 'SYSTEM_BOT', 'ACCOUNTANT', name='user_role'),
               server_default=None,
               comment='User role for access control.',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Whether user can login.',
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Bypass all permission checks.',
               existing_nullable=False)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last successful login timestamp.',
               existing_nullable=True)
    op.drop_constraint(op.f('users_seatalk_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('vendor', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_seatalk_id_key'), 'users', ['seatalk_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last successful login timestamp.',
               existing_nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Bypass all permission checks.',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='Whether user can login.',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('ADMIN', 'WAREHOUSE_OP', 'SALES_REP', 'SYSTEM_BOT', 'ACCOUNTANT', name='user_role'),
               server_default=sa.text("'WAREHOUSE_OP'::user_role"),
               comment=None,
               existing_comment='User role for access control.',
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Display name.',
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Bcrypt hashed password.',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='User email address (optional).',
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Unique username for login.',
               existing_nullable=False)
    op.alter_column('purchase_order_item', 'total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('purchase_order_item', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('purchase_order', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.create_index(op.f('ix_product_variant_variant_name_fts'), 'product_variant', [sa.literal_column("to_tsvector('simple'::regconfig, COALESCE(variant_name, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_product_variant_full_sku_fts'), 'product_variant', [sa.literal_column("to_tsvector('simple'::regconfig, COALESCE(full_sku, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.alter_column('product_variant', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='Soft-delete flag for discontinued variants.',
               existing_nullable=False)
    op.alter_column('product_variant', 'zoho_sync_status',
               existing_type=postgresql.ENUM('PENDING', 'SYNCED', 'ERROR', 'DIRTY', name='zoho_sync_status_enum'),
               server_default=sa.text("'PENDING'::zoho_sync_status_enum"),
               existing_comment='Sync status with Zoho.',
               existing_nullable=False)
    op.alter_column('product_variant', 'condition_code',
               existing_type=postgresql.ENUM('N', 'R', 'U', name='condition_code_enum'),
               comment='N (New), R (Repair), or NULL (Used/Default).',
               existing_comment='N (New), R (Refurbished), U (Used), or NULL.',
               existing_nullable=True)
    op.create_index(op.f('ix_identity_identity_name'), 'product_identity', ['identity_name'], unique=False)
    op.alter_column('product_identity', 'is_stationery',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Flags stationery items. Stationery identities must be Product type and single-SKU.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('product_identity', 'weight',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Identity weight in pounds.',
               existing_nullable=True)
    op.alter_column('product_identity', 'dimension_height',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Identity height in inches.',
               existing_nullable=True)
    op.alter_column('product_identity', 'dimension_width',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Identity width in inches.',
               existing_nullable=True)
    op.alter_column('product_identity', 'dimension_length',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment=None,
               existing_comment='Identity length in inches.',
               existing_nullable=True)
    op.alter_column('product_identity', 'identity_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Human-friendly identity name (e.g., group or component identity name).',
               existing_nullable=True)
    op.alter_column('product_identity', 'type',
               existing_type=postgresql.ENUM('Product', 'B', 'P', 'K', 'S', name='identity_type_enum'),
               comment='B (Bundle), P (Part), K (Kit), S (Service), Base (Product).',
               existing_comment='Product (standard), B (Bundle), P (Part), K (Kit).',
               existing_nullable=False)
    op.create_index(op.f('ix_product_family_base_name_fts'), 'product_family', [sa.literal_column("to_tsvector('simple'::regconfig, COALESCE(base_name, ''::character varying)::text)")], unique=False, postgresql_using='gin')
    op.alter_column('product_family', 'family_code',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='Zero-padded family code derived from product_id (e.g., 00001).',
               existing_nullable=False)
    op.alter_column('platform_listing', 'sync_status',
               existing_type=postgresql.ENUM('PENDING', 'SYNCED', 'ERROR', name='platform_sync_status_enum'),
               server_default=sa.text("'PENDING'::platform_sync_status_enum"),
               existing_comment='PENDING (needs push), SYNCED (clean), ERROR (retrying).',
               existing_nullable=False)
    op.alter_column('platform_listing', 'upc',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='UPC/GTIN used by marketplace listing.',
               existing_nullable=True)
    op.alter_column('platform_listing', 'listing_condition',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Platform-specific condition label/value as raw string.',
               existing_nullable=True)
    op.alter_column('platform_listing', 'listing_type',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Platform-specific listing type/classification label.',
               existing_nullable=True)
    op.alter_column('platform_listing', 'listing_quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Channel-specific listing quantity/stock shown on platform.',
               existing_nullable=True)
    op.alter_column('platform_listing', 'merchant_sku',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Marketplace merchant SKU for fallback lookup only.',
               existing_nullable=True)
    op.alter_column('platform_listing', 'external_ref_id',
               existing_type=sa.VARCHAR(length=100),
               comment='The ID on the remote platform (Zoho Item ID, ASIN).',
               existing_comment='Canonical platform listing ID (not merchant SKU).',
               existing_nullable=True)
    op.alter_column('platform_listing', 'variant_id',
               existing_type=sa.BIGINT(),
               comment='The specific item being sold.',
               existing_comment='Matched internal SKU variant; NULL means unresolved listing.',
               existing_nullable=True)
    op.drop_constraint('uq_order_platform_external_id', 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_zoho_id'), table_name='orders')
    op.drop_index('ix_order_status', table_name='orders')
    op.drop_index('ix_order_platform', table_name='orders')
    op.drop_index('ix_order_ordered_at', table_name='orders')
    op.drop_index('ix_order_external_id', table_name='orders')
    op.create_unique_constraint(op.f('uq_orders_platform_external_id'), 'orders', ['platform', 'external_order_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_platform'), 'orders', ['platform'], unique=False)
    op.create_index(op.f('ix_orders_ordered_at'), 'orders', ['ordered_at'], unique=False)
    op.create_index(op.f('ix_orders_external_id'), 'orders', ['external_order_id'], unique=False)
    op.alter_column('orders', 'zoho_sync_status',
               existing_type=postgresql.ENUM('PENDING', 'SYNCED', 'ERROR', 'DIRTY', name='zoho_sync_status_enum'),
               server_default=sa.text("'PENDING'::zoho_sync_status_enum"),
               existing_comment='Outbound Zoho sync status.',
               existing_nullable=False)
    op.alter_column('orders', 'fulfillment_channel',
               existing_type=postgresql.ENUM('SELF_FULFILLED', 'AMAZON_FBA', name='order_fulfillment_channel_enum'),
               comment=None,
               existing_comment='SELF_FULFILLED or AMAZON_FBA.',
               existing_nullable=False,
               existing_server_default=sa.text("'SELF_FULFILLED'::order_fulfillment_channel_enum"))
    op.alter_column('orders', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Order ingestion source (ECWID_API, WALMART_API, CSV_GENERIC, etc.).',
               existing_nullable=False,
               existing_server_default=sa.text("'MANUAL'::character varying"))
    op.alter_column('order_item', 'total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Total price (quantity * unit_price).',
               existing_comment='Total price (quantity × unit_price).',
               existing_nullable=False)
    op.alter_column('order_item', 'variant_id',
               existing_type=sa.BIGINT(),
               comment='Matched internal product variant.',
               existing_comment='Denormalized matched variant for query speed.',
               existing_nullable=True)
    op.alter_column('order_item', 'platform_listing_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Resolved platform listing for this order line.',
               existing_nullable=True)
    op.alter_column('inventory_item', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'SOLD', 'RESERVED', 'RMA', 'DAMAGED', name='inventory_status_enum'),
               server_default=sa.text("'AVAILABLE'::inventory_status_enum"),
               existing_comment='AVAILABLE, SOLD, RESERVED, RMA, DAMAGED.',
               existing_nullable=False)
    op.alter_column('integration_state', 'platform_name',
               existing_type=sa.VARCHAR(length=50),
               comment='Logical platform key, e.g. AMAZON, EBAY_USAV.',
               existing_comment="Logical platform key, e.g. 'AMAZON', 'EBAY_USAV'.",
               existing_nullable=False)
    op.alter_column('customer', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment="Soft-delete flag; maps to Zoho 'inactive' status.",
               existing_nullable=False)
    op.alter_column('customer', 'source',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Latest known customer acquisition source (ECWID_API, WALMART_API, SHIPSTATION_CSV, etc.).',
               existing_nullable=True)
    op.alter_column('bundle_component', 'role',
               existing_type=postgresql.ENUM('Primary', 'Accessory', 'Satellite', name='bundle_role_enum'),
               server_default=sa.text("'Primary'::bundle_role_enum"),
               existing_comment='Context: Primary, Accessory, Satellite.',
               existing_nullable=False)
    op.alter_column('bundle_component', 'quantity_required',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_comment='How many of this component are needed.',
               existing_nullable=False)
    op.drop_index(op.f('ix_physical_scans_tracking_number'), table_name='physical_scans')
    op.drop_index('ix_physical_scans_tracking', table_name='physical_scans')
    op.drop_index('ix_physical_scans_scanned_at', table_name='physical_scans')
    op.drop_table('physical_scans')
    # ### end Alembic commands ###
