"""add order verification and packing metadata columns

Revision ID: ef489e27f5ff
Revises: 0037
Create Date: 2026-07-03 14:01:56.185467+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef489e27f5ff'
down_revision: Union[str, None] = '0037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('verify_status', sa.String(length=50), server_default='UNVERIFIED', nullable=True, comment='Verification status: UNVERIFIED, VERIFIED, READY, ERROR_MISSING_TRACKING, ERROR_COUNT_MISMATCH.'))
    op.add_column('orders', sa.Column('packing_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True, comment='Metadata containing links to Synology NAS photos.'))
    op.drop_index(op.f('ix_return_record_fulfillment_channel'), table_name='return_record')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_return_record_fulfillment_channel'), 'return_record', ['fulfillment_channel'], unique=False)
    op.drop_column('orders', 'packing_metadata')
    op.drop_column('orders', 'verify_status')
    # ### end Alembic commands ###
